### ISSUE TITLE
script for latex images

### ISSUE THREAD

**Issue by algeboy** [thetensor-space/thetensor-space.github.io#1]
We have a number of latex images and that will grow.  We use pdflatex and convert (see readme in latex folder) to make these into PNG files.

I'd like a simple script/batch file to sit in the latex folder and it runs over all the *.tex files in there and terms them into PNGs by running pdflatex and convert.

**Comment by joshmaglione** [comment]
Working on this at the moment on branch `JFM`. I'm assuming everything that should be compiled from tex files to image files should be located in `./latex/`. Let me know if this isn't correct. 

Maybe a global object is created that runs through all the images and outputs them into `./uploads/images/`? Might that be useful?
