### ISSUE TITLE
Stage 2 - Support calendar events 

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#10]
"Events:  This will be where we want to host not only upcoming but also old events, such as TACA 2019 and GCG 2014.  I'll also want to put info on there about local seminars in CSU/Boulder."

[UPDATE 10-16-2019]
@algeboy this is the main big feature that needs to be implemented asap so we can complete the site before December. **Once you confirm how I should implement this, I can get started.**

#### Again, this is how this feature would work:

1. You add an event on Google Calendar.
2. The event automatically shows up on the site with the description you gave on the event.

#### We can also avoid using Google Calendar by adding events as .md files. It'd work like this:

1. You add a `2019-10-16-event-name.md` file.
2. The new event shows up on the `events` page

**Would you like to use Google Calendar, or add events posts?**

**Comment by Alex-Cannon** [comment]
[The Google Calendar Events API](https://developers.google.com/calendar/v3/reference) supports up to 1,000,000 requests per day. I think it would be a wise decision to use Google Calendar to track events.

How this would work is this:
1. Contributors would add an event to their Google Calendar.
2. When users visit "/events" or "/" (home), all upcoming and or past events will be displayed.
3. Users can find more information either on the event itself, or the event can link to an external or internal page with more information.

@algeboy What are your thoughts?

**Comment by algeboy** [comment]
Sounds good, perhaps with one small addition.  I have a back log of events,but which have content to share.  Would these need to appear on the Calendar or could they simply be listed below the calendar?

**Comment by Alex-Cannon** [comment]
@algeboy you could do it either way you wanted. You'd have a calendar page, which displays events in some way. On the same page, you could add whatever content you wanted to the page.

You could also link to internal or external articles in the event description, which users would be able to view on the site.

Does that answer your question?

**Comment by Alex-Cannon** [comment]
I'm also curious how you'd like the events displayed on the site.

My first thoughts are making it look like so:
![Traditional Calendar](https://data.whicdn.com/images/333179978/original.jpg?t=1563911187)

Or, more like a list on the articles page.

What are your thoughts?

**Comment by algeboy** [comment]
No, events here are much more spread apart, typically a couple weeks apart, somethings should show up even a year in advance if it is a conference announcement. so we don't want weekly rather just lists of events in order.  something like the cards on teh packages page will do fine.

**Comment by Alex-Cannon** [comment]
Alright, great. I'll make a list similar to the articles page, ordered from earliest to latest. Would you like to hide past events?

Also, you'll need to **choose a google account** to create these events on. I would recommend creating / using a separate google account so personal events are not mixed into the site.

**Comment by algeboy** [comment]
@Alex-Cannon  the.tensor.space@gmail.com

**Comment by Alex-Cannon** [comment]
@algeboy now that you mentioned  that events are a couple weeks apart, I think it'd be easier for you to add events on Jekyll rather than having them on Google Calendar. That way more people can edit / add events more easily.

**@algeboy would you like to use Google Calendar or Jekyll for your events?**

**Comment by algeboy** [comment]
a jekyll format is fine.

**Comment by Alex-Cannon** [comment]
Alright, sounds good
