### ISSUE TITLE
Packages in /articles should be moved to new "packages" page.

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#11]
Presenelty articles is serving up info about packages, that should be something different.  We should move those to the packages link

This may be able to be achieved by tagging posts.

**Comment by Alex-Cannon** [comment]
@algeboy I'm confused on this issue.

We have a "Software / Tools" page on the site. From what I understand, this page will dynamically display your repositories: #8 

From what I understand, you would like the following:

1. A "Software / Tools" page to dynamically showcase repositories
2. A "Packages" page to showcase packages

Is this correct?

**Comment by algeboy** [comment]
Yes, these are slightly different.  Some repos are more dynamic and split or merge based on development needs, but packages are stable and thought out and have documentation themes to follow.  So these are separate.

**Comment by Alex-Cannon** [comment]
Great. Thanks for the clarification. I'll create a separate "packages" page for stable repositories for this issue.
