### ISSUE TITLE
Make university logos on "about" all the same size or at least proportional.

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#12]
@algeboy we have a few options to achieve this. I would recommend this solution:

If you provide logos that are relatively similar in aspect ratio, I will make them the same height. This will effectively give you your results.

I would suggest finding logos that are square as I think they'd look the best together.

Another option is to zoom in on the pictures I currently have. I wouldn't recommend this because it would be difficult to recognize the logos.

**Comment by algeboy** [comment]
There should be multiple sizes to choose from here:
 * CSU https://brand.colostate.edu/logo/
 * Bucknell https://www.bucknell.edu/communications/guidelines-policies/bucknell-style-guide
 * Kent https://www.kent.edu/ucm/kent-state-university-logo
 * For Bielefled, use what is there as I don't understand german enough to know where to point.
 * Use this for NSA ![image](https://user-images.githubusercontent.com/23457935/65623004-199e6980-df84-11e9-8ef2-09af265ffe28.png)
 * Use the following for NSF https://www.nsf.gov/policies/logos.jsp
 * Use this for Simons Foundation ![image](https://user-images.githubusercontent.com/23457935/65623189-7ac63d00-df84-11e9-8545-5f8bdff23fe3.png)

**Comment by Alex-Cannon** [comment]
@algeboy I have decent, roughly 1:1 logos for all the universities. The exception is Bielefled.

They have a logo, but I think it's difficult to tell which university it is: [see their square logo](https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwijhvSo1OzkAhVQtZ4KHf8xDNIQjRx6BAgBEAQ&url=https%3A%2F%2Fekvv.uni-bielefeld.de%2Fblog%2Funinews%2Fentry%2Fbielefeld_university_among_the_top&psig=AOvVaw39IU2B1fUzKeP6jQQUw_rn&ust=1569524422335957)

Currently, we're using [this logo](https://www.google.com/url?sa=i&source=imgres&cd=&cad=rja&uact=8&ved=2ahUKEwiO--un1OzkAhXO7Z4KHemqB74QjRx6BAgBEAQ&url=https%3A%2F%2Feuraxess.ec.europa.eu%2Fworldwide%2Fbrazil%2Ferc-preparative-fellowship-bielefeld-university-germany-promising-young&psig=AOvVaw0t7PD2eI896oz8NILPLLeR&ust=1569524441584217) from them.

Also, would you like a logo for HIM Hausdorff institute for Mathematics? Currently, we have a logo, but it is a banner and not square. Where can I find a roughly 1:1 logo for them?

Or is the [current logo](https://www.him.uni-bonn.de/fileadmin/templates/him/images/Logo_him_4c_xxl.gif) ok? I can also photoshop just the "HIM" out of this logo to make it closer to a 1:1 ratio.

**Comment by Alex-Cannon** [comment]
[Here is a screenshot with the new logos](https://drive.google.com/open?id=1IMAauMEKPeKjviCtOGrDjy8BzY2xQXc1). I imagine we want to change some images?
