### ISSUE TITLE
Stage 2 - Support Reveal.js slides in posts

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#17]
@algeboy I think this issue is straight-forward. [Here is an example of what your markup might look like](https://github.com/hakimel/reveal.js/#markup).

I want to confirm that we want to use reveal.js slides for slide shows. Another option is for me to develop a custom slide show for the site.

**Comment by algeboy** [comment]
Not sure what a custom slide show would be like but what happens is that others give us slides.  Usually as PDFs but sometimes as Reveal.JS.  Some people host this themselves, say off of Slides.com, and then we just link to that.  so maybe that's enough

**Comment by Alex-Cannon** [comment]
Ok. What we can do is I can create a special component for a RevealJS link and for downloading a PDF that is on a post. That way people can view the slides.

I can also add support for a custom slide show that you have the option to use. Would you still like to support RevealJS slide shows on the site?

**Comment by Alex-Cannon** [comment]
@algeboy you can easily link to a PDF or to slides.com as the site is now, so I went ahead and moved this to `ready for review`. Let me know if we want to support RevealJS slides on the site.

**Comment by algeboy** [comment]
fine.
