### ISSUE TITLE
Stage 2 - Add documentation for all types of content on the site.

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#18]
* General site questions
* Blog posts
    * Packages
    * Articles
    * Events
* Reveal.js slides
* Video content
* Event Calendar
* RX.js / KaTex.js
* Adding Documentation

@algeboy let me know if I missed anything I need to add documentation for.

**Comment by Alex-Cannon** [comment]
My plan is to add markdown files in /site_docs for each documentation page. Then, add a CONTRIBUTING.md file for contributors to read which will link to important markdown files.

Is this acceptable?

**Comment by algeboy** [comment]
Good plan, this list looks great.

**Comment by Alex-Cannon** [comment]
@algeboy I'll be adding documentation soon. I think a great place to put it would be in the wiki section of github. What are your thoughts?
