### ISSUE TITLE
Stage 2 - Support Video Content in posts

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#24]
@algeboy where will you host your videos? My first thought is hosting your videos on YouTube.

My first thoughts on making this work is to create a special component you can use. It would look something like this in your markdown file:

**{% include embedVideo.html src="link-to-youtube-video" %}**

So, it'd be really easy to add a video to a blog post. Let me know your thoughts on this and also if you plan to use YouTube to host your videos.

**Comment by algeboy** [comment]
YouTube or Vimeo.  That solution looks good.  Ideally the videos would each have a page as you say in markdown with the meta details: date, event, speaker, possible slides or notes.

**Comment by Alex-Cannon** [comment]
Yep, you could have a page with as many slides, videos, or notes you'd like. I think I have what I need to be able to create this component. Let me know if you have any other questions.

**Comment by Alex-Cannon** [comment]
@algeboy I have this working. Below is an example of how this works:

```
---
title: Densor
---

{% include video.html url="https://youtu.be/T1itpPvFWHI" title="Jekyll" desc="Jekyll tutorial"%}
```

How it looks on a page:

![How it looks on a post](https://raw.githubusercontent.com/Alex-Cannon/thetensor-space.github.io/dev/tmp_images/video_link.png)

When users click the video:

![How it looks after you click it](https://raw.githubusercontent.com/Alex-Cannon/thetensor-space.github.io/dev/tmp_images/video_clicked.png)

We also have the option of making the video look more like how it does on my [blog](https://alex-cannon.github.io/portfolio), where the video thumbnails are shown on the page instead of the component we have now.

Let me know which you prefer and we can go from there.

**Comment by algeboy** [comment]
looks great. make a pull request.
