### ISSUE TITLE
Stage 2 - Add optional sidebar to posts

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#26]
@algeboy where do you want this sidebar? What content / links do you want in it?

**Comment by algeboy** [comment]
on the docs page leave it as is.  One the articles pages probably imitate blogs and have articles by interest level or dates posted.  The rest wont need sidebars

**Comment by Alex-Cannon** [comment]
Ok great. I'll add a sidebar to article pages, which will have some common links and suggestions. I'll get into more details as I develop this.

**Comment by Alex-Cannon** [comment]
Below is a screenshot of the sidebar working. Let me know if there are any changes I should make to it.

![tensor space sidebar](https://user-images.githubusercontent.com/28692645/66347642-0a1f0900-e912-11e9-9471-0513b44e5600.png)

**Comment by algeboy** [comment]
This looks great. keep it.

**Comment by Alex-Cannon** [comment]
I'm going to re-open this until I make a pull request with the sidebar. The work is done, I just need to make a PR.

**Comment by Alex-Cannon** [comment]
See pr #29
