### ISSUE TITLE
Stage 3 - Package main links

### ISSUE THREAD

**Issue by joshmaglione** [thetensor-space/thetensor-space.github.io#27]
I think at the top of every package page (below title and date), we should have 3 links:
1. Latest release,
2. Repo,
3. Documentation.

We can point to latest releases with the following blueprint:
https://github.com/FOO/BAR/releases/latest

I would expect the link to 3 would take the user to either the Docs part of the website or the documentation file location on github. Someone can decide.

**Comment by algeboy** [comment]
This is good to do

**Comment by Alex-Cannon** [comment]
I'll get this done in stage 3 or issue #21 

@algeboy @joshmaglione I need to know if we'd like a link to the docs part of the site or the docs on github (this can easily be changed in the future).

**Comment by algeboy** [comment]
fine to do in stage 3

**Comment by joshmaglione** [comment]
@Alex-Cannon for now, I would say point to github docs since there is something there. Eventually, we will migrate. 

@algeboy chime in if you want.
