### ISSUE TITLE
Stage 2 - Add package layout and new package link

### ISSUE THREAD

**Issue by joshmaglione** [thetensor-space/thetensor-space.github.io#28]
The package layouts should not be so different. I think it would nice, and save us time in the future, to have a consistent layout for all packages. Here's a suggestion that I can implement eventually if desired.

Create a folder `_packages/` or `_software/` whatever. Fill the directory with md files for each package. For example, here's one for TensorSpace.

```
---
layout: package-layout
name: TensorSpace
---

The **markdown** description here if wanted.
```

One can create one `html` file for all the packages, similar to how one would create a blog layout in Jekyll. From just the name, we can point people to the latest releases with something like:
`https://github.com/thetensor-space/{{ package.name }}/releases/latest`

This way, we need only input data into the md files, and we get a consistent looking html page for all the packages. Future edits can then just be done to the layout file.

**Comment by algeboy** [comment]
I don't understand the suggestion, what two categories are you comparing to when you say "shouldn't be so different?"

One point perhaps I see: Yes we don't want a lot to maintain.  Problem though is that our repo structure doesn't necessarily represent our package structure.  Repos we create and some are experimental or convenience or trying to separate concepts.  Packages seem to be polished.  That is my only thought.  Can you explain a bit more what you are invisioning seeing Josh?

**Comment by joshmaglione** [comment]
Only discussing website layout and design. We should (or I can) create a layout page for packages, e.g. `package-layout.html`. In it will be html code creating a package page. Jekyll will run through all the files in the, say, `_software/` directory and produce an html page for each md file in `_software/`. It should work just like blog posts work in Jekyll.

The main advantage is design changes can be centralized to one location, `package-layout.html` for example. Every time we add a new package, we just add an md file with metadata and a description. Formatting does not need to be considered every time we want to add a new package. 

This also has the advantage of making all package pages have the same format. 

As for your concern about repo structure, add a flag to the meta data. For example 
```
---
experimental: True
---
```
When running through the files, peel off the experimental packages and do something special with those. When it's no longer experimental, set to `False` or delete the tag. Or one can just delete the md file to remove the package from the website. 

Am I making sense? This is nothing about *actual* design, and more about preventing repeated work.

**Comment by algeboy** [comment]
Fine, so each package follows a template, yes, that I agree with.  Lets do that.  I think lets have Alex put that together as he already knows how it affects the theme and we can just suggest how to adapt.

**Comment by Alex-Cannon** [comment]
@algeboy @joshmaglione I'll quickly go over how packages work in `/dev`  (this will be documented in #9 :

### File Structure
```
_posts
  2019-10-16-your-package-name.md
```

### Package front matter example:
```
---
layout: post
title:  Densor
categories: [ Tools ]
image: assets/images/densor.jpg
package: true
---
```

* Note: We're using the "post" layout for packages. **I can attach a screenshot if requested.**

### Package link:
```
/articles/YOUR_PACKAGE_NAME
```

**Would you help confirm the changes we want?** From what I gathered, we'd like these changes:

1. A packages layout
2. Add a new link for a packages:` /{{ package.name }}/releases/latest`
3. Add a new `/packages` folder

Is this correct? 

(Also, be sure to `@mention` me so I can respond to issues faster. Thanks!)

**Comment by algeboy** [comment]
@Alex-Cannon seems fine.

**Comment by Alex-Cannon** [comment]
@algeboy great. I'll add these changes.

**Comment by Alex-Cannon** [comment]
See #32 to view my PR
