### ISSUE TITLE
TAGA workshop pages down

### ISSUE THREAD

**Issue by algeboy** [thetensor-space/thetensor-space.github.io#61]
The workshop portion pages are somehow not rendering after the most recent pull....hmmm.

**Comment by cliu587** [comment]
Possibly an issue with caching? Working locally on my side. (To refresh and avoid cache, command-shift-R or ctrl-shift-R)

<img width="1058" alt="Screenshot 2024-05-19 at 10 04 16 PM" src="https://github.com/thetensor-space/thetensor-space.github.io/assets/11726498/bd419c0d-3fc6-416e-803f-ca63d6d8f4a2">


<img width="1075" alt="Screenshot 2024-05-19 at 10 02 59 PM" src="https://github.com/thetensor-space/thetensor-space.github.io/assets/11726498/4d9df5ff-ec89-457b-8783-17a6ceaff593">

**Comment by cliu587** [comment]
closing - reopen if you can reproduce/if it's an issue on certain browsers.
