### ISSUE TITLE
Stage 2 - Support Software / Tools dynamically loads a list of GitHub repos under thetensor-space. 

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#8]
Software/Tools.  This link should load a list of the GitHub repos that are on "TheTensor-Space" Git organization.  Maybe this can be automatically updateing, so if we add or merge repos it shows up.  It would be nice to have a blurb of each, e.g. if it stripped off the first few lines from the readme.

**Comment by Alex-Cannon** [comment]
@algeboy I have the base functionality down for this issue. All repositories from thetensor-space are pulled onto this page automatically. Below is a screenshot of it working:

![Dynamic Repositories](https://raw.githubusercontent.com/Alex-Cannon/thetensor-space.github.io/dev/tmp_images/dynamic_repositories.jpg)

**What data do you want displayed for each repository?** Right now, we're displaying the title (which links to the repository) and the description of the repository. We can pull data like forks, stars, description, README.md, etc. [as described in the GitHub API](https://developer.github.com/v3/repos/#get).

I was thinking we'd use the "card" from the articles page to display these instead of the way I have them now.

**Comment by algeboy** [comment]
I like the idea of the cards.  We can pull up a snippet of the readme.  These will include a simple starement of the content and maybe a graphic or a list of authors.

**Comment by Alex-Cannon** [comment]
Alright, great. I'll add snippets of the README.md, title, a link to the repo, and authors, then I'll make a new comment with my progress.

**Comment by Alex-Cannon** [comment]
@algeboy it is done. Below is a screenshot of the software / tools page. It lists all the repositories with authors, 200 characters of the README.md, title, and links to the repositories.

![Software Cards done](https://raw.githubusercontent.com/Alex-Cannon/thetensor-space.github.io/dev/tmp_images/software%20tools%20card%20done.png)

I had an issue where some of the repositories had a file called "README" instead of "README.md", so my scripts had trouble getting all the README files. When I was unable to get the README, I used the repository description instead.

**If you rename all your "README" files to "README.md for each repository, the issue will be fixed.**

From what you see here, are there any other changes I should make?

**Comment by algeboy** [comment]
@Alex-Cannon great
