### ISSUE TITLE
Add documentation for adding docs

### ISSUE THREAD

**Issue by Alex-Cannon** [thetensor-space/thetensor-space.github.io#9]
@algeboy : "Docs looks super cool, but we need instructions on how to use it.  If we could include those instructions in the webpage that would be super since this is afterall an open source project and users will need those instructions.  Some something about the file structure and links to the use of jeykll or this particular theme."

The theme provides documentation for adding docs. See the /_site_docs/docs.md for supporting documentation. **The /_site_docs repository contains instruction provided in the base theme. Any additional documentation I create will be added to this folder.**

**@algeboy once you've reviewed this, let's close the issue.**

**Comment by algeboy** [comment]
not sure where to look for this change, didn't find it.  Could we have a link to this somewhere, perhaps a link on the top bar called "Contribute" in which we can given guidelines and links to this.

**Comment by Alex-Cannon** [comment]
@algeboy the /site_docs folder [on the dev branch](https://github.com/thetensor-space/thetensor-space.github.io/tree/dev) contains markdown files with instructions on how to use the theme. These were provided by default by the docs theme. I'll also add more documentation in this directory.

Sure. My first thoughts are to create a "Contribute" link on the top navbar, which links to CONTRIBUTING.md on github. Here, I'd detail how to contribute and links to the documentation.

Does this work for you? Or would you prefer having a separate page on the site itself?

**Comment by Alex-Cannon** [comment]
#18 includes documentation for adding docs. I'll close this issue as these are the same.
